version: 2
updates:

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/ui"
    target-branch: "develop"
    reviewers:
      - "rangerrick"
      - "mikewrosey"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/core/web-assets/"
    target-branch: "foundation-2021"
    versioning-strategy: "increase-if-necessary"
    reviewers:
      - "rangerrick"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "d3"
      - dependency-name: "ionicons"
      - dependency-name: "@types/lodash"
      - dependency-name: "@types/node"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "foundation-2019"
    reviewers:
      - "rangerrick"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
