commands:
  run-build:
    description: "Run the main build"
    parameters:
      number-vcpu:
        default: 8
        type: integer
      node-memory:
        default: echo "NODE_OPTIONS Not Set"
        type: string
      vaadin-javamaxmem:
        default: 2g
        type: string
    steps:
      - cached-checkout
      - save-cached-checkout
      - extract-pom-version
      - run:
          name: Check for Releasability
          command: |
            export OPENNMS_VERSION="$(.circleci/scripts/pom2version.sh pom.xml)"
            .circleci/scripts/release-lint.sh "${OPENNMS_VERSION}"
      - restore-maven-cache
      - restore-nodejs-cache
      - run:
          name: Compile OpenNMS
          command: |
            ulimit -n 65536 || :
            mkdir -p ~/.m2
            echo "${GPG_SECRET_KEY}" | base64 -d > ~/.m2/sign-key.asc
            export SIGN_KEY_PASS="$(echo "${GPG_PASSPHRASE}" | base64 -d)"
            export OPENNMS_VERSION="$(.circleci/scripts/pom2version.sh pom.xml)"
            << parameters.node-memory >>
            export MAVEN_OPTS="-Xmx12g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            MAVEN_ARGS="--settings .circleci/settings.xml install"
            mkdir -p target/artifacts
            case "${CIRCLE_BRANCH}" in
              "master-"*|"release-"*|"develop")
                # "production" build will also enable javadoc and such
                MAVEN_ARGS="-Dbuild.type=production $MAVEN_ARGS"
                ;;
            esac
            case "${CIRCLE_BRANCH}" in
              "master-"*)
                # "production" build should build SBOM manifests
                MAVEN_ARGS="-Dbuild.sbom=false $MAVEN_ARGS"
                ;;
            esac
            echo "export OPENNMS_VERSION=\"$OPENNMS_VERSION\"" >> $BASH_ENV
            ./compile.pl -DskipTests=true -Dbuild.skip.tarball=false \
              -Daether.connector.resumeDownloads=false \
              -Daether.connector.basic.threads=1 \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DvaadinJavaMaxMemory=<< parameters.vaadin-javamaxmem >> \
              -DmaxCpus=<< parameters.number-vcpu >> \
              -Prun-expensive-tasks \
              -Psmoke \
              --batch-mode \
              $MAVEN_ARGS || exit 1
            ./compile.pl -s .circleci/scripts/structure-settings.xml \
              --batch-mode \
              --fail-at-end \
              -Prun-expensive-tasks \
              -Pbuild-bamboo \
              org.opennms.maven.plugins:structure-maven-plugin:1.0:structure || exit 1
      - run:
          name: Check if we have generated apidocs
          command: |
            if [ -d target/site/apidocs ] && [ "$(find target/site/apidocs -name \*.html | wc -l)" -gt 1 ]; then
              pushd target/site/apidocs
                tar -czf "../../artifacts/opennms-${OPENNMS_VERSION}-javadoc.tar.gz" *
              popd
            fi
      - run:
          name: Remove Extra Maven Repository OpenNMS Files
          command: |
            # move these out of the way so they're not stored in the maven pre-cache
            cd ~/.m2/repository/org/opennms
            mkdir /tmp/maven-keep
            mv $(ls -1 | grep -v -E '^(jicmp-api|jicmp6-api|jrrd-api|jrrd2-api|lib|maven)$') /tmp/maven-keep
      - persist-project-changes
      - save-maven-cache
      - run:
          name: Restore Extra Maven Repository OpenNMS Files
          command: |
            # now move them back so they end up in the workspace for builds further down the workflow
            mv /tmp/maven-keep/* ~/.m2/repository/org/opennms/
      - save-nodejs-cache
      - store_artifacts:
          path: ~/project/target/artifacts
          destination: artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - project/target/structure-graph.json
            - .m2/repository/org/opennms
            # is this even necessary anymore?
            - .artifacts
