commands:
  update-maven-cache:
      description: "Maven: Refresh local repository from POM files"
      steps:
        - run:
            name: Collect Maven Dependencies
            command: |
              ./compile.pl -t \
                -Dbuild.skip.tarball=true \
                --update-plugins \
                -Daether.connector.resumeDownloads=false \
                -Daether.connector.basic.threads=1 \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -Pbuild-bamboo \
                -Prun-expensive-tasks \
                -Psmoke \
                -Denable.license=true \
                --batch-mode \
                dependency:resolve-plugins \
                de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
