jobs:
  minion-image:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - build-image-single-arch:
          architecture: linux/amd64
          container_name: minion
          dct: true
