version: '3.8'
services:
  db:
    image: postgres:15
    container_name: opennms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres   # set your postgres password
      POSTGRES_DB: opennms
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

