jobs:
  horizon-deb-build:
    executor: build-executor
    resource_class: large
    steps:
      - sign-packages/setup-env:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
      - cached-checkout
      - attach_workspace:
          at: ~/
      - restore-maven-cache
      - run:
          name: Build Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=2
            export MAVEN_OPTS="-Xmx5g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh opennms
      - sign-packages/sign-debs:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: target/debs/*.deb
      - run:
          name: Gather system logs
          when: always
          command: |
            mkdir -p ~/build-results/system-logs
            (dmesg || :) > ~/build-results/system-logs/dmesg 2>&1
            (ps auxf || :) > ~/build-results/system-logs/ps 2>&1
            (free -m || :) > ~/build-results/system-logs/free 2>&1
            (docker stats --no-stream || :) > ~/build-results/system-logs/docker_stats 2>&1
      - store_artifacts:
          when: always
          path: ~/build-results
          destination: build-results
      - store_artifacts:
          path: ~/project/target/debs
          destination: debs
      - cache-workflow-assets:
          cache_prefix: deb-horizon
          source_path: target/debs
