jobs:
  tarball-assembly-only:
    executor: build-executor
    resource_class: large
    parameters:
      number-vcpu:
        default: 6
        type: integer
      vaadin-javamaxmem:
        default: 1g
        type: string
    steps:
      - cached-checkout
      - attach_workspace:
          at: ~/
      - restore-maven-cache
      - run:
          name: Assemble tarballs and related artifacts
          command: |
            ulimit -n 65536 || :
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            export MAVEN_ARGS="install"
            cp .circleci/settings.xml ${HOME}/.m2
            # release branches should enable extra "production" stuff like license indexing
            case "${CIRCLE_BRANCH}" in
              "master-"*|"release-"*|"develop")
                MAVEN_ARGS="-Dbuild.type=production $MAVEN_ARGS"
                ;;
            esac
            case "${CIRCLE_BRANCH}" in
              "master-"*)
                MAVEN_ARGS="-Dbuild.sbom=false $MAVEN_ARGS"
                ;;
            esac
            ulimit -n 65536 || :
            ./assemble.pl -DskipTests=true -Dbuild.skip.tarball=false \
              -Daether.connector.resumeDownloads=false \
              -Daether.connector.basic.threads=1 \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DvaadinJavaMaxMemory=<< parameters.vaadin-javamaxmem >> \
              -DmaxCpus=<< parameters.number-vcpu >> \
              -Denable.license=true \
              -Pbuild-bamboo \
              -Prun-expensive-tasks \
              -Dopennms.home=/opt/opennms \
              --batch-mode \
              $MAVEN_ARGS || exit 1
      - run:
          name: Collect Artifacts
          command: |
            mkdir -p target/{artifacts,config-schema,tarballs}
            OPENNMS_VERSION="$(.circleci/scripts/pom2version.sh pom.xml)"
            find ./target -name "*.tar.gz" -type f -not -iname '*source*' -exec cp {} "./target/tarballs/opennms-${OPENNMS_VERSION}.tar.gz" \;
            find ./opennms-full-assembly/target -name "*-core.tar.gz" -type f -not -iname '*source*' -exec cp {} "./target/tarballs/opennms-${OPENNMS_VERSION}-core.tar.gz" \;
            find ./opennms-assemblies/minion/target -name "*.tar.gz" -type f -not -iname '*source*' -exec cp {} "./target/tarballs/minion-${OPENNMS_VERSION}.tar.gz" \;
            find ./opennms-assemblies/sentinel/target -name "*.tar.gz" -type f -not -iname '*source*' -exec cp {} "./target/tarballs/sentinel-${OPENNMS_VERSION}.tar.gz" \;
            cp ./opennms-assemblies/xsds/target/*-xsds.tar.gz "./target/artifacts/opennms-${OPENNMS_VERSION}-xsds.tar.gz"
            cp target/*-source.tar.gz ./target/artifacts/
            cp opennms-full-assembly/target/generated-sources/license/THIRD-PARTY.txt ./target/artifacts/
      - store_artifacts:
          when: always
          path: ~/project/target/artifacts
          destination: artifacts
      - store_artifacts:
          when: always
          path: ~/project/target/tarballs
          destination: tarballs
